### ISSUE TITLE
build error on ubuntu 16 cuda 9

### ISSUE THREAD

**Issue by toptim** [KlausT/ccminer#87]
Ubuntu 16.04.3 LTS
Cuda compilation tools, release 9.0, V9.0.176
Driver Version: 384.90
`/usr/local/cuda/bin/nvcc -gencode=arch=compute_61,code=sm_61 -I/usr/local/cuda/include -I. -O3 -std=c++11 -Xcompiler -Wall -D_FORCE_INLINES --ptxas-options="-v" -o neoscrypt/cuda_neoscrypt_tpruvot.o -c neoscrypt/cuda_neoscrypt_tpruvot.cu
In file included from neoscrypt/cuda_neoscrypt_tpruvot.cu:10:0:
./miner.h:16:21: fatal error: jansson.h: No such file or directory
compilation terminated.
Makefile:1925: recipe for target 'neoscrypt/cuda_neoscrypt_tpruvot.o' failed
make[2]: *** [neoscrypt/cuda_neoscrypt_tpruvot.o] Error 1
`
maybe i need make some changes in Makefile.am?

**Comment by KlausT** [comment]
Or you could just installl libjansson-dev on your system

**Comment by toptim** [comment]
Thanks, success build
Maybe add libjansson-dev to requires libraries to be built under linux?

**Comment by ksze** [comment]
@toptim 

What nvidia driver and cuda toolkit did you use? The ones from the graphics-drivers PPA? Or the ones from nvidia website?

And isn't CUDA 9 supposed to cause problems with lyra2v2? Have you tried mining that?

Did you just run the build.sh script?

I've been having trouble building on Ubuntu 17.10. If it's much easier to build using Ubuntu 16.04, I might just downgrade my Ubuntu. #80

**Comment by toptim** [comment]
Ubuntu 16.04.3 LTS
Cuda compilation tools, release 9.0, V9.0.176
Driver Version: 384.90
cuda from nvidia (network edition)
run just build.sh
`Cuda error in func 'blakeKeccak256_cpu_hash_80' at line 687 : invalid device pointer.
Cuda error in func 'bmw256_cpu_hash_32' at line 308 : driver shutting down.
`
lyra2v2 on cuda 9 not work et

**Comment by KlausT** [comment]
Yes, lyra2v2 doesn't work with CUDA 9.
I don't know why.

**Comment by FlorinAndrei** [comment]
@KlausT FYI, I've been mining lyra2v2 (Monacoin and Vertcoin) with ccminer-tpruvot, compiled from source on Ubuntu 16.04, with the Nvidia drivers 387.34 from the PPA, and CUDA 9.1.85, and it seems to be working just fine.

I have not tried yet to compile ccminer-KlausT but I may give it a try. If you guys could add the pascal algorithm, that would be the killer app for me, I could finally ditch sgminer which uses too much CPU.

**Comment by KlausT** [comment]
Yes, lyra2v2 works with CUDA 9.1, looks like CUDA 9.0 is broken.
Some months ago I tried to add pascal, but obviously I'm not smart enough, since I coudn't make it work.

**Comment by EnforcerE** [comment]
I manage to get no more than 350 H/s mining xmr on my gigabyte gtx 1050 ti, while using ethminer i get up to 12 MH/s. Is it so due to incrased difficulty?

**Comment by KlausT** [comment]
Looks like you are comparing two different algos.
