### ISSUE TITLE
Doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by 88plug** [KlausT/ccminer#29]
Beta 8.0.9 build broken

make[2]: Entering directory '/root/klaust/ccminer-8.09'
g++ -DHAVE_CONFIG_H -I.  -fopenmp  -pthread -fno-strict-aliasing -I./compat/jansson -Iyes/include  -DSCRYPT_KECCAK512 -DSCRYPT_CHACHA -DSCRYPT_CHOOSE_COMPILETIME   -g -O2 -MT ccminer-ccminer.o -MD -MP -MF .deps/ccminer-ccminer.Tpo -c -o ccminer-ccminer.o `test -f 'ccminer.cpp' || echo './'`ccminer.cpp
ccminer.cpp:13:30: fatal error: cuda_runtime_api.h: No such file or directory
 #include "cuda_runtime_api.h"
                              ^
compilation terminated.
Makefile:1271: recipe for target 'ccminer-ccminer.o' failed

and

8.08
~/klaust/ccminer-8.08 # ./autogen.sh
Makefile.am:58: error: blank line following trailing backslash
Makefile.am:73: error: ccminer_SOURCES must be set with '=' before using '+='
Makefile.am:6: warning: JANSSON_INCLUDES was already defined in condition TRUE, which includes condition WANT_JANSSON ...
Makefile.am:4: ... 'JANSSON_INCLUDES' previously defined here

**Comment by 88plug** [comment]
Fixed it!  

`apt-get install -y python3-dev`

then

```
wget https://github.com/KlausT/ccminer/archive/8.09.zip
unzip 8.09.zip
cd ccminer-8.09
```

add CMakeLists.txt with

```
touch CMakeLists.txt
echo 'add_compile_options(-std=c++11)' >> ./CMakeLists.txt
```

```
./autogen.sh
./configure.sh
make -B 
```
#the -B flag clears any cache and starts a clean build.
